git:
  depth: 1
jobs:
  include:

    - language: node_js
      node_js:
      - 8
      cache:
        directories:
        - node_modules
      script:
      - npm run lint
      - npm run test-coveralls

    - stage: before_deploy
      if: branch = master   # Build only the master branch
      language: minimal
      name: Build Docker image and push to Docker Hub registry
      services: docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t nirdizatiresearch/predict-react:$TRAVIS_COMMIT .
      - docker build -t nirdizatiresearch/predict-react .
      - docker push nirdizatiresearch/predict-react:$TRAVIS_COMMIT
      - docker push nirdizatiresearch/predict-react

    - stage: deploy
      if: branch = master   # Deploy only the master branch
      dist: xenial
      name: Server deployment
      language: minimal
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh
