git:
  depth: 1
jobs:
  include:

    - language: node_js
      node_js:
      - 8
      cache:
        directories:
        - node_modules
      script:
      - npm run lint
      - npm run test-coveralls

    - stage: before_deploy
      language: minimal
      name: Build Docker image and push to Docker Hub registry
      services: docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t nirdizatiresearch/predict-react:$TRAVIS_COMMIT .
      - docker build -t nirdizatiresearch/predict-react .
      - docker push nirdizatiresearch/predict-react:$TRAVIS_COMMIT
      - docker push nirdizatiresearch/predict-react

    - stage: deploy
      dist: xenial
      name: Server deployment
      language: minimal
      deploy:
        provider: script
        skip_cleanup: true
        script: bash deploy.sh

before_install:
- openssl aes-256-cbc -K $encrypted_6a567f0c75d9_key -iv $encrypted_6a567f0c75d9_iv
  -in cloud.key.enc -out ./cloud.key -d
